import createTransporter from '../config/emailConfig.js';
import dotenv from 'dotenv';
dotenv.config();

export const sendEmail = async (req, res) => {
  try {
    
    const { name, email, phone, message } = req.body;
    const blueprintFile = req.file; 

    if (!name || !email || !phone || !message) {
      return res.status(400).json({ success: false, message: 'Name, email, phone, and message are required fields.' });
    }

    
    const transporter = createTransporter();

    const htmlContent = `
    <div style="font-family: 'Helvetica Neue', Arial, sans-serif; color: #333; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
      <h1 style="color: #2c3e50; text-align: center;">You Have Received a New Quote</h1>
      <h3 style="color: #555; text-align: center;">Paradise Estimate Submission</h3>
      <p style="font-size: 14px; color: #555;">A new quote request has been submitted through the Estimating Hub website. Details are below:</p>

      <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <tr style="background-color: #f9f9f9;">
          <td style="padding: 10px; font-weight: bold; border: 1px solid #ddd;">Name</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${name}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; border: 1px solid #ddd;">Email</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${email}</td>
        </tr>
        <tr style="background-color: #f9f9f9;">
          <td style="padding: 10px; font-weight: bold; border: 1px solid #ddd;">Phone</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${phone}</td>
        </tr>
        <tr>
          <td style="padding: 10px; font-weight: bold; border: 1px solid #ddd;">Message</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${message}</td>
        </tr>
        <tr style="background-color: #f9f9f9;">
          <td style="padding: 10px; font-weight: bold; border: 1px solid #ddd;">Blueprint Included</td>
          <td style="padding: 10px; border: 1px solid #ddd;">${blueprintFile ? 'Yes' : 'No'}</td>
        </tr>
      </table>

      <p style="margin-top: 20px; font-size: 12px; color: #777; text-align: center;">
        This email was automatically generated by Estimating Hub. Please do not reply directly to this email.
      </p>
    </div>
    `;

    const mailOptions = {
      from: process.env.FROM_EMAIL || 'noreply@estimatinghub.com',
      to: process.env.EMAIL_USER || 'estimatinghub788@gmail.com',
      subject: `You Have Received a New Quote for Paradise Estimate`,
      html: htmlContent,
      attachments: blueprintFile ? [
        {
          filename: blueprintFile.originalname,
          content: blueprintFile.buffer
        }
      ] : [],
    };

    await transporter.sendMail(mailOptions);

    return res.status(200).json({ success: true, message: 'Email sent successfully!' });

  } catch (error) {
    console.error('Error sending email:', error);
    return res.status(500).json({ 
      success: false, 
      message: 'Failed to send email. Please try again later.', 
      error: error.message 
    });
  }
};
